ALTER TABLE USER_LIST DROP CONSTRAINT fk_department_id;
ALTER TABLE DEPARTMENTS DROP CONSTRAINT fk_department_head;
ALTER TABLE PERMISSIONS DROP CONSTRAINT fk_permissions_emp_id;
ALTER TABLE PERMISSIONS DROP CONSTRAINT fk_permissions_role_id;
ALTER TABLE ACCOUNTS DROP CONSTRAINT fk_accounts_emp_id;
ALTER TABLE DOCUMENTS DROP CONSTRAINT fk_documents_t_id;

DROP TABLE USER_LIST;
DROP TABLE ROLE_LIST;
DROP TABLE PERMISSIONS;
DROP TABLE DEPARTMENTS;
DROP TABLE ACCOUNTS;
DROP TABLE DOCUMENTS;


CREATE TABLE USER_LIST (
    emp_ID NUMBER(10) PRIMARY KEY,
    user_name VARCHAR(50) UNIQUE,
    password_hash NUMBER(20),
    lname VARCHAR2(50),
    fname VARCHAR2(50),
    mname VARCHAR2(50),
    email VARCHAR2(50),
    phone VARCHAR2(50),
    super_ID NUMBER(10),
    dept_ID NUMBER(10)
);

CREATE TABLE DEPARTMENTS (
    dept_ID NUMBER(10) PRIMARY KEY,
    dept_name VARCHAR(50),
    emp_id NUMBER(10) UNIQUE
);

CREATE TABLE ROLE_LIST (
    ROLE_ID NUMBER(10) PRIMARY KEY,
    TITLE VARCHAR2(20)
);
INSERT INTO ROLE_LIST VALUES (0, 'Associate');
INSERT INTO ROLE_LIST VALUES (1, 'Department Head');
INSERT INTO ROLE_LIST VALUES (2, 'Benefits Coordinator');

CREATE TABLE PERMISSIONS (
    emp_ID NUMBER(10) NOT NULL,
    role_ID NUMBER(10) NOT NULL
);

CREATE TABLE ACCOUNTS (
    t_ID NUMBER(10) PRIMARY KEY,
    FY NUMBER(4) NOT NULL,
    emp_ID NUMBER(10),
    transaction_amount NUMBER(10,2),
    status NUMBER(1),
    timeVal NUMBER(38),
    address VARCHAR2(200),
    start_date VARCHAR2(20),
    grade VARCHAR(100)
);

CREATE TABLE DOCUMENTS (
    doc_url VARCHAR2(255) PRIMARY KEY,
    t_ID NUMBER(10)
);

ALTER TABLE USER_LIST ADD CONSTRAINT fk_department_id FOREIGN KEY (dept_id) REFERENCES DEPARTMENTS(dept_id);
ALTER TABLE DEPARTMENTS ADD CONSTRAINT fk_department_head FOREIGN KEY (emp_id) REFERENCES USER_LIST(emp_id);
ALTER TABLE PERMISSIONS ADD CONSTRAINT fk_permissions_emp_id FOREIGN KEY (emp_id) REFERENCES user_list(emp_id) ON DELETE CASCADE;
ALTER TABLE PERMISSIONS ADD CONSTRAINT fk_permissions_role_id FOREIGN KEY (role_id) REFERENCES role_list(role_id) ON DELETE CASCADE;
ALTER TABLE ACCOUNTS ADD CONSTRAINT fk_accounts_emp_id FOREIGN KEY (emp_id) REFERENCES user_list(emp_id) ON DELETE CASCADE;
ALTER TABLE DOCUMENTS ADD CONSTRAINT fk_documents_t_id FOREIGN KEY (t_id) REFERENCES accounts(t_id) ON DELETE CASCADE;


